### ISSUE TITLE
TypeError: Cannot read property 'answer_code' of undefined

### ISSUE THREAD

**Issue by peter-russell** [tjhorner/MakerbotWebUI#7]
After running `node index`, the following error appears:

```
C:\Users\Administrator\Documents\MakerbotWebUI-master\node_modules\makerbot-rpc\index.js:241
          answer_code: codeBody.answer_code
                                ^

TypeError: Cannot read property 'answer_code' of undefined
    at Request.request [as _callback] (C:\Users\Administrator\Documents\MakerbotWebUI-master\node_modules\makerbot-rpc\index.js:241:33)
    at self.callback (C:\Users\Administrator\Documents\MakerbotWebUI-master\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\Administrator\Documents\MakerbotWebUI-master\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Before this, it does say that it has connected to the printers.

**Comment by tjhorner** [comment]
Thanks, I'll look into this next week when I actually have access to some printers.

Can I get some more information about how you're connecting to the printers? E.g. are you using Thingiverse auth, local auth, or something else?

**Comment by tjhorner** [comment]
Ok, so it seems there's an issue with my `makerbot-rpc` library. I have no clue how it worked before, but it's entirely broken right now.

It's a simple one-line fix, and it seems to work fine again!

<img width="836" alt="image" src="https://user-images.githubusercontent.com/2646487/56518871-68d40000-64f5-11e9-8651-28546a5215b0.png">

**Comment by tjhorner** [comment]
Ok, I pushed the fix. Can you run `npm install makerbot-rpc@1.0.11` and see if your issue is fixed?

**Comment by peter-russell** [comment]
It doesn't crash anymore when `node index` is run, and the printers are being detected, but they are showing as 'Disconnected'. 

> Can I get some more information about how you're connecting to the printers? E.g. are you using Thingiverse auth, local auth, or something else?

Apologies, just saw this. We normally use MakerBot Print to connect and print to the printers. So I'm connecting via IP.

**Comment by tjhorner** [comment]
Are you able to visit your printer's web server? You should see a directory listing:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/2646487/56603521-ba8f8f80-65b4-11e9-963f-1b59b0924308.png">

Also, are your logs spammed with `[printer_name] [status]`? (This is something I put in for debugging but forgot to remove, apparently lol)

<img width="206" alt="image" src="https://user-images.githubusercontent.com/2646487/56603565-ca0ed880-65b4-11e9-8151-f3cc3c187d21.png">

**Comment by peter-russell** [comment]
Yep, the printer's web server is accessible:
![image](https://user-images.githubusercontent.com/6551599/56619735-ea4c9f00-6669-11e9-946a-6a972f0968cd.png)

> Also, are your logs spammed with `[printer_name] [status]`?

In the CLI there is only a `Connected to printer` line.

I have looked at the printer's web server, and in the apache_error_log.log it has `AH01630: client denied by server configuration: /usr/local/apache2/error`

The client IP it lists matches that of the server.

**Comment by peter-russell** [comment]
Do I need to change the `authMethod` in the config.json to "local" or something like that? Or does it have to be thingiverse?

**Comment by tjhorner** [comment]
You shouldn't need to change the config, no. Since it just stalls after the "Connected to printer" line, I'm thinking something is going wrong with authentication. I don't have a printer on-hand right now, but there should be something in the printer's settings about Thingiverse cloud services or something. Try clearing all access from there.

After that, try booting up the server again. Your printer's LED ring should start flashing yellow and prompt you to press the knob to authenticate your Thingiverse account.

I had to do this earlier for some reason. Hope it isn't a recurring issue.

**Comment by peter-russell** [comment]
I cleared all accounts from the printer, rebooted the server and authorised the connection on the printer when the ring started flashing yellow. Still showing up as "Disconnected" on the "Manage printers" page.

**Comment by tjhorner** [comment]
Very weird. I will look into this more tomorrow and make some tools to aid in debugging this.

**Comment by peter-russell** [comment]
Thanks

**Comment by peter-russell** [comment]
Just wondering if there are any more updates?

**Comment by tjhorner** [comment]
Hey, sorry; been busy. AP tests coming up.

Still will look into this when I have the time. Probably next week.
